# Generated by Django 5.1.3 on 2024-11-12 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fileinfo',
            options={'verbose_name': 'File info', 'verbose_name_plural': 'File infos'},
        ),
    ]
